### ISSUE TITLE
Did this break on latest fugitive?

### ISSUE THREAD

**Issue by devth** [shumphrey/fugitive-gitlab.vim#10]
Upgraded and it doesn't work (opens empty browser). Maybe [this commit](https://github.com/tpope/vim-fugitive/commit/245ce889e2a6eb318cec865cf787e7bb0cb8aa95) is a problem (not sure just guessing).

**Comment by shumphrey** [comment]
hmm, I can't recreate, it still works for me.
I guess you could confirm what happens when you run `git remote get-url origin` and what version of git you have?

**Comment by devth** [comment]
Returns the `git@` url, same as `git config --get remote.origin.url`.

`git version 2.11.0`.

**Comment by shumphrey** [comment]
It seems unlikely to me that the linked commit is the cause here.
The root url to open comes from the `let g:fugitive_gitlab_domains` in your vimrc file not from fugitive.

What does vim echo when you run `:Gbrowse!` (with the exclamation mark)

**Comment by devth** [comment]
Weird, `:Gbrowse!` shows the expected url, so it has something to do with how vim is opening it in the browser?

**Comment by shumphrey** [comment]
fugitive has an FAQ in the readme that says

>:Gbrowse delegates to git web--browse, which is less than perfect when it comes to finding the right browser. You can tell it the correct browser to use with git config --global web.browser .... On OS X, for example, you might want to set this to open. See git web--browse --help for details.

Is any of that relevant?

**Comment by shumphrey** [comment]
If `:Gbrowse!` echos the right url, then the right url is being returned to fugitive.
What happens after that isn't under gitlab-fugitive's control.

The code for opening the browser lives somewhere around here
https://github.com/tpope/vim-fugitive/blob/f44845e4408aae03e018e98afb7fbf0c2ee87dd5/plugin/fugitive.vim#L2331-L2348

**Comment by devth** [comment]
@shumphrey thanks for your help debugging! I'll continue investigating on the fugitive side.

**Comment by devth** [comment]
It had something to do with my `open` not working in tmux / iterm2. Restarting machine fixed it 😭
