### ISSUE TITLE
Support linking to line of code by html anchors

### ISSUE THREAD

**Issue by 1e0ng** [shumphrey/fugitive-gitlab.vim#13]
Is it possible to open the link with anchors at gitlab?
For example,

http://demo.mygitlab.com/a/b/c#L20

and

http://demo.mygitlab.com/a/b/c#L20-22

**Comment by shumphrey** [comment]
Yes,

fugitive's `:Gbrowse` supports ranges and so does fugitive-gitlab.

i.e. you can visually select a block and then :Gbrowse and that range will be shown in gitlab

**Comment by 1e0ng** [comment]
Awesome, thanks! 👍
