### ISSUE TITLE
g:fugitive_gitlab_domains should default to ['https://gitlab.com']

### ISSUE THREAD

**Issue by mcepl** [shumphrey/fugitive-gitlab.vim#2]
I would think that there are now so many gitlab repos on https://gitlab.com that it would make sense to default to it, so that the beginner user wouldn't have to bother with setting `g:fugitive_gitlab_domains`.

**Comment by shumphrey** [comment]
I agree.
Will implement this asap.

**Comment by shumphrey** [comment]
Implemented it the same way fugitive defaults to github.com
