### ISSUE TITLE
Gbrowse fails with "fugitive: 'origin' is not a supported remote"

### ISSUE THREAD

**Issue by wellsjo** [shumphrey/fugitive-gitlab.vim#22]
my vimrc looks like this
```vim
Plug 'tpope/vim-fugitive'
Plug 'shumphrey/fugitive-gitlab.vim'

let g:fugitive_gitlab_domains = ['https://gitlab-myserver.private.org']
let g:gitlab_api_keys = {'gitlab-myserver.private.org': 'my-access-token'}
```

and whenever I run `:Gbrowse`, vim responds with:  
```
fugitive: 'origin' is not a supported remote
```

Is this a bug or something wrong with my config? Thank you!

**Comment by shumphrey** [comment]
Hello,

What is the output of `git remote -v`

**Comment by shumphrey** [comment]
And also, what is the output of `:echo g:fugitive_browse_handlers` (inside vim)

**Comment by wellsjo** [comment]
```
> git remote -v
origin  git@gitlab-01:private/dev.git (fetch)
origin  git@gitlab-01:private/dev.git (push)
```

```
:echo g:fugitive_browse_handlers
[function('gitlab#fugitive_handler'), function('<SNR>121_github_url'), function('<SNR>121_instaweb_url')]
```

@shumphrey

**Comment by shumphrey** [comment]
Given that `let g:fugitive_gitlab_domains = ['https://gitlab-myserver.private.org']` is presumably not the real value, does the bit after `https://` exactly match the value between `git@HERE:private/dev.git`

i.e. does "gitlab-01" match "gitlab-myserver.private.org"

It looks like its missing the fully qualified domain part `private.org`, perhaps you need:

 `let g:fugitive_gitlab_domains = ['https://gitlab-myserver.private.org', 'https://gitlab-myserver']` or similar

**Comment by wellsjo** [comment]
@shumphrey you are correct, I'm not using a typical setup here. 

> does "gitlab-01" match "gitlab-myserver.private.org"  

no, `gitlab-01` is the name of the server, which is an alias in my ssh config (used as the remote). `gitlab-myserver.private.org` is the gitlab url I want to open. `gitlab-01` has to be the remote, because that has SSH access. 

So I added `'https://gitlab-01'` to my `fugitive_gitlab_domains`, and now a page opens, but it's with `gitlab-01` in the url instead of `gitlab-myserver.private.org`. 

Is there a way to accomplish what I'm trying to do?

**Comment by shumphrey** [comment]
Currently it is not possible for the remote to not match the gitlab url specified in `fugitive_gitlab_domains`

Could you not do something like...

in ~/.ssh/config have an alias for `gitlab-myserver.private.org` where Host is really gitlab-01

```
Host gitlab-myserver.private.org
    Hostname gitlab-01
```

Then your repo is cloned with `git clone git@gitlab-myserver.private.org` but git really uses gitlab-01.
Your vimrc keeps the ['https://gitlab-myserver.private.org'] value?

You can also do this in ~/.gitconfig though I'm not sure if it helps
```
[url "git@gitlab-myserver.private.org:"]
    InsteadOf = git@gitlab-01:
```

That would mean that a `git clone git@gitlab-01:my/repo` would actually use gitlab-myserver.private.org which ssh would actually use gitlab-01 for...

Some combination must be possible there.
I currently don't see an easy solution inside vim itself.

**Comment by wellsjo** [comment]
ah, nice tip. editing my `~/.gitconfig` with the `InsteadOf` worked! thank you!
