### ISSUE TITLE
Add support for different git ssh users

### ISSUE THREAD

**Issue by MarcelRobitaille** [shumphrey/fugitive-gitlab.vim#24]
The plugin is not working for me. I have tracked the problem down to the regex [here](https://github.com/shumphrey/fugitive-gitlab.vim/blob/b8e7b6986c5d13f3e2de2163816af06f74a6f838/autoload/gitlab.vim#L74). The problem is that my GitLab ssh user is `gitlab` not `git`. I know this is not standard and probably means that I set up GitLab incorrectly, but do you think it would be possible to update the regex? I have confirmed that changing it to `...\|git\%(lab\)\?@\|ssh://git\%(lab\)\?\|...` works.

I am also running ssh on a port other than 22. Maybe it is possible to add `let base = substitute(base, ':\d\{1,4}\/', '/', '')` to strip the port before [`let base = tr(base, ':', '/')`](https://github.com/shumphrey/fugitive-gitlab.vim/blob/b8e7b6986c5d13f3e2de2163816af06f74a6f838/autoload/gitlab.vim#L76)?

**Comment by shumphrey** [comment]
I'm open to PRs for this.
The test suite will need updating https://github.com/shumphrey/fugitive-gitlab.vim/blob/master/test/gbrowse.vader

**Comment by MarcelRobitaille** [comment]
Ok I'll work on a PR. I'll make sure to do tests too. I also wonder how to handle subdomains. My gitlab instance is at `gitlab.myhost.com` but when I clone it's `ssh://gitlab@myhost.com`. If I set `g:fugitive_gitlab_domains` to `myhost.com`, `Gbrowse` will match but it won't send me to the right place. If I set it to `gitlab.myhost.com`, `Gbrowse` come up empty.

**Comment by shumphrey** [comment]
Can't you clone from the subdomain?

**Comment by MarcelRobitaille** [comment]
I can but it's not what shows up in GitLab when I copy the link. I'll look into changing that.

**Comment by MarcelRobitaille** [comment]
Yeah that was an easy fix. I just had to change `produtction.gitlab.ssh_host` in `/etc/webapps/gitlab/gitlab.yml`. I'll close this when #25 is merged.

**Comment by shumphrey** [comment]
There may also be gitconfig that helps, e.g. `[InsteadOf]` or ssh config that helps.
ssh can be told to map one domain to another via config.
git can be told to replace one (part of) a connection string with another.
