### ISSUE TITLE
[FeatureRequest] Browse file use branch name

### ISSUE THREAD

**Issue by hiberabyss** [shumphrey/fugitive-gitlab.vim#32]
Sometimes, I need a url to track the latest status of file, this could be accomplished via branch name in the url. Thanks!

**Comment by shumphrey** [comment]
This is already supported, see Fugitive docs

**Comment by shumphrey** [comment]
Well, I'm struggling to recreate, but that functionality would come from fugitive anyway

**Comment by shumphrey** [comment]
`:Gbrowse :%`

**Comment by hiberabyss** [comment]
Thanks for your reply!

What I need is to use `master` instead of commit hash in the url, however, could not find any method to do this in both Fugitive doc and readme.

**Comment by shumphrey** [comment]
Make sure you're using the latest fugitive, seems to be the default for me

**Comment by hiberabyss** [comment]
Seems worked after upgrade `fugitive`. Thanks!
