### ISSUE TITLE
GBrowse open file to correct line

### ISSUE THREAD

**Issue by vegerot** [shumphrey/fugitive-gitlab.vim#33]
In other IDEs (VSCode and WebStorm), opening in GitLab will not just open the current file, but also will open it to the same line your cursor is on.  It would be nice to have this in `GBrowse` too

**Comment by shumphrey** [comment]
It already does that.
See fugitive docs

**Comment by vegerot** [comment]
My b. So in your opinion the fastest way to do this is to do `v:GBrowse`?  Thank you so much, and apologies for not reading `:h GBrowse`.  I read other issues at first and when you said to look at the docs I had assumed you meant the README

**Comment by shumphrey** [comment]
> My b. So in your opinion the fastest way to do this is to do `v:GBrowse`? Thank you so much, and apologies for not reading `:h GBrowse`. I read other issues at first and when you said to look at the docs I had assumed you meant the README

Visual mode is what I tend to do. You can probably do some local binding to shortcut the current line

**Comment by vegerot** [comment]
Thank you 🙏.  Have a good one and wash your hands 🧼!

**Comment by vegerot** [comment]
stay clean ;)
