### ISSUE TITLE
Performance degradation when using Omnifunc completion.

### ISSUE THREAD

**Issue by qasimwarraich** [shumphrey/fugitive-gitlab.vim#38]
Hey first of all thank you for your hard work with this plug in!

I noticed that it seems to work quite well with casual `GBrowse`ing and so without providing any credentials but as soon as I supply a `let g:gitlab_api_keys = {'gitlab.com': 'glPATgoeshere'}` I can noticeably see my typing lag in a git commit message window. Is this something you can replicate on your end? Having direct issues integration is a super cool feature for the work flow but it seems to create this weird side affect of prohibitively slow typing. 

I have included a gif of this behaviour below. For what it's worth I experience the same issue with Rhubarb. Perhaps it's a curl thing or something on my end. In either case would be very happy to hear back and help address what may be going on. 

cheers!

Gif of observed behaviour: 
![slow](https://user-images.githubusercontent.com/37380474/155439513-f4cedf02-00bc-4415-88e6-ea640355148c.gif)

**Comment by shumphrey** [comment]
The omnifunc only triggers when you press the omnifunc key combo (usually ctrl-x ctrl-o)
It shouldn't cause any slowness on typing.

I'd suggest removing all plugins and config except fugitive and fugitive-gitlab to see if you can recreate this.
Do you have a plugin or keymap that is triggering on every key stroke?

**Comment by qasimwarraich** [comment]
Thanks for the response! I will try a minimal config and report back. 

I thought it maybe related to this plugin as the slow typing  behaviour only appeared after installing this plug in (and Rhubarb). Moreover when I remove the `let g:gitlab_api_keys` global variable from my config the typing slowness goes away. I noticed the same behavior with Rhubarb. In the case of Rhubarb the behaviour is gone when I don't source the plugin in my config.

**Comment by shumphrey** [comment]
It sounds like you have something triggering omnicomplete on every keystroke.
Some sort of completion plugin or keybinding.

**Comment by qasimwarraich** [comment]
This makes sense, I will dig a bit deeper. I was unable to replicate the issue with a minimal config 😅. Sorry for the false alarm, I suffered a bit of confirmation bias when I saw that removing the global variable fixed the issue.

**Comment by qasimwarraich** [comment]
Wow actually seemed to have found the culprit. It was my completion engine `nvim-cmp` (forgot to provide context that I was on neovim, apologies). I had recently added omnicomplete as a source for the auto completions. The author mentions this as potentially concerning for performance as omnifunc is quite slow. I had done this originally for the `vim-tex` plugin as it provides it's completions via omnicomplete. There is actually a discussion about this constellation of omnifuncing [here](https://github.com/lervag/vimtex/issues/2215) . To reach a usable compromise I have setup a omnifunc completion to only source when the file type is `tex`. 

Again apologise for the false alarm but perhaps this may help someone in the future with similar issues. If there is anything I could help you out with I would be more than happy to hear it and thank you again for the cool plugin. 

Cheers!

**Comment by qasimwarraich** [comment]
The one thing I can think of is to implement a way to source the `gitlab_api_keys` either from a system environment variable or `.netrc`. Don't want to leave raw token strings in my config file as it is under VCS. Would be happy to hear your thoughts on the matter and may potentially open another issue or better a PR 😉.
