### ISSUE TITLE
Please provide a LICENSE or COPYING file

### ISSUE THREAD

**Issue by praiskup** [shumphrey/fugitive-gitlab.vim#39]
I know that `:help license` is referenced, but still - for the re-packaging to
Linux distributions - it is a good idea to provide a copy of the license file.

At least I, as Fedora packager, am sort of pushed to at least try to
request this:
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

**Comment by shumphrey** [comment]
I'll add it asap.

**Comment by shumphrey** [comment]
Now using MIT license file with b73a8e97de95d26280082abb7f51465a3d3b239e

**Comment by praiskup** [comment]
Thank you!

**Comment by praiskup** [comment]
FTR, trying to get into Fedora: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2103073
