### ISSUE TITLE
Gbrowse not working

### ISSUE THREAD

**Issue by MuschPusch** [shumphrey/fugitive-gitlab.vim#4]
I get this error running: Gbrowse

```
fugitive: Instaweb failed to start and 'origin' is not a supported remote
```

I added to my .vimrc

```
let g:fugitive_gitlab_domains = ['https://ourdomain.com']
```

**Comment by shumphrey** [comment]
You can get that for a few reasons
- fugitive-gitlab is not loaded into vim
- fugitive.vim is an old version that doesn't support plugins.
- Your repo doesn't have origin url containing ourdomain.com

What version of fugitive.vim are you using?

**Comment by shumphrey** [comment]
type:

```
:echo g:fugitive_browse_handlers
```

It should echo something like:

```
[function('<SNR>25_gitlab_fugitive_handler'), function('<SNR>24_github_url'), function('<SNR>24_instaweb_url')]
```

If it says undefined variable, your fugitive.vim is too old
If the first element isn't gitlab_fugitive_handler, then this plugin hasn't been loaded into vim correctly.

**Comment by MuschPusch** [comment]
:echo g:fugitive_browse_handlers

gives me:

```
[function('<SNR>110_gitlab_fugitive_handler'), function('<SNR>88_github_url'), function('<SNR>88_instaweb_url')]
```

**Comment by shumphrey** [comment]
Ok, so next question, what does origin contain:

```
git remote -v
```

The domain (only the domain part) must match what you put in let g:fugitive_gitlab_domains
e.g.

```
origin  git@gitlab.mydomain.com:mygroup/myproject.git
```

would be 

```
let g:fugitive_gitlab_domains = ['https://gitlab.mydomain.com']
```

The domain part should match exactly.

**Comment by MuschPusch** [comment]
Vim:
:echo g:fugitive_gitlab_domains

```
source.mydomain.com
```

git remove -v

```
origin  ssh://git@source.mydomain.com:2222/my/repo.git (fetch)
```

Hm... So the port definition is messing things up?

**Comment by shumphrey** [comment]
ok yes, I can recreate this.
This form of URL doesn't currently work.
I'll have a look to see what needs changing.

**Comment by MuschPusch** [comment]
Thanks!

**Comment by tillydray** [comment]
I seem to be having a similar issue.

`git remote -v` gives me `origin  ssh://git@ssh.domain.io:port/my/repo.git`

So if I have this in my vimrc `let g:fugitive_gitlab_domains = ['ssh.domain.io']` and do `GBrowse` I get this output in a new buffer: `**warning** (netrw) shell signalled an error`. And I get this output in the command line `ssh.domain.io/path/to/file.txt`. However, the url I need to open is `domain.io/path/to/file.txt`, in other words strip `ssh.` from the front of the url.

If I change `fugitive_gitlab_domains` to `['domain.io']` I get an (expected) error `fugitive: No Gbrowse handler installed for 'ssh://git@ssh.domain.io:port/my/repo.git'`

**Comment by shumphrey** [comment]
> I seem to be having a similar issue.
> 
> `git remote -v` gives me `origin ssh://git@ssh.domain.io:port/my/repo.git`
> 
> So if I have this in my vimrc `let g:fugitive_gitlab_domains = ['ssh.domain.io']` and do `GBrowse` I get this output in a new buffer: `**warning** (netrw) shell signalled an error`. And I get this output in the command line `ssh.domain.io/path/to/file.txt`. However, the url I need to open is `domain.io/path/to/file.txt`, in other words strip `ssh.` from the front of the url.
> 
> If I change `fugitive_gitlab_domains` to `['domain.io']` I get an (expected) error `fugitive: No Gbrowse handler installed for 'ssh://git@ssh.domain.io:port/my/repo.git'`

If you're using non standard web vs git URLs your best bet is to configure something like ~/.ssh/config to alias your hosts or do some git configuration

**Comment by shumphrey** [comment]
@JasonMFry See comments on #22
