### ISSUE TITLE
Add CI linting and CI file merging (Have working solution)

### ISSUE THREAD

**Issue by tsjordan-eng** [shumphrey/fugitive-gitlab.vim#40]
Do you have any interest in adding commands that lint the CI file or return a merged one? I created some commands for my own vimrc that do this. I could clean them up and I could add them to the repo.

https://docs.gitlab.com/ee/api/lint.html

```vim

let g:fugitive_gitlab_domains = ['https://gitlab.com']
let g:gitlab_api_keys = {'gitlab.com': 'xxxxxxxxxxxxxxxxxxxx'}

function! CiLint()
  echo system("jq --null-input --arg yaml \"$(<".bufname().")\" --arg branch $(git branch --show-current) '.content=$yaml|.ref=$branch' | curl --header \"Content-Type: application/json\" --header \"PRIVATE-TOKEN: ".g:gitlab_api_keys['gitlab.com']."\" \"https://cee-gitlab.com/api/v4/ci/lint\" --data @- -s | jq '.errors'")
endfunction
function! CiMerge()
    execute("%!jq --null-input --arg yaml \"$(<".bufname().")\" --arg branch $(git branch --show-current) '.content=$yaml|.ref=$branch|.include_merged_yaml=true' | curl --header \"Content-Type: application/json\" --header \"PRIVATE-TOKEN: ".g:gitlab_api_keys['gitlab.com']."\" \"https://cee-gitlab.com/api/v4/ci/lint\" --data @- -s |jq -r '.merged_yaml' ")
endfunction


command! CiLint call CiLint()
command! CiMerge call CiMerge()

```

**Comment by shumphrey** [comment]
I'm definitely open to this if you want to raise a PR.

The thing I'm not sure about yet is the `command` bits, this plugin currently has no commands of its own, though I've various branches that experiment with issue commands.

I'd add the functions to autoload/gitlab/ci.vim, then either leave the commands in your own vimrc or put them in plugin/gitlab.vim

**Comment by shumphrey** [comment]
You can see autoload/gitlab/api.vim for existing styles

**Comment by shumphrey** [comment]
I'm closing this for now, but feel free to raise a PR
