### ISSUE TITLE
**warning** (netrw) shell signalled an error

### ISSUE THREAD

**Issue by ArtemKushnerov** [shumphrey/fugitive-gitlab.vim#41]
I get the following message on GBrowse

<img width="877" alt="image" src="https://user-images.githubusercontent.com/6704859/210253375-48c38581-0344-4370-9ea5-3cd531fb16b9.png">

what could be the issue?

**Comment by shumphrey** [comment]
Its fugitive.vim that handles the actual opening on URLs.
I believe there's a FAQ or help page on this topic over there.

**Comment by shumphrey** [comment]
Also, its netrw that's showing that error, you might want to look at the help pages for netrw, but failing that, search the github issues on fugitive for netrw
