### ISSUE TITLE
GBrowse not working for commit buffers

### ISSUE THREAD

**Issue by phantomwhale** [shumphrey/fugitive-gitlab.vim#43]
Apologies if my terminology is a little off here, and I'm also new to gitlab, so this might not be a "general" issue.

## Background

We have github repositories merged into gitlab, and after the migration process have updated the git remote to point at gitlab instead. All of which is to say that could be the reason for this issue.

The `:GBrowse` command is working correctly from file views, but not from commit views

## How to recreate

- Open a file in vim under Gitlab version control 
- run `:GBrowse` and the file opens up correctly in Gitlab 👌 (e.g. https://gitlab.com/MY_ORG/MY_SUBGROUP/MY_PROJECT/blob/80d4ad4c4480753588ab87533ecb4b2a3299a5b9/FILE_NAME)
- run `:Git blame`, pick any line in the blame, and hit return
- the buffer should now be showing the "commit" view - with the green and red lines, the `tree` and `parent` lines at the top etc....
- run `:GBrowse` and the Gitlab opens up with a 404 👎 (e.g. https://gitlab.com/MY_ORG/MY_SUBGROUP/MY_PROJECT/commit/56f016eb16ff32911c2a76825acfc7093cc48e62)

## Workaround

Just manually add `/-` after MY_PROJECT seems to produce the correct URL structure (e.g. https://gitlab.com/MY_ORG/MY_SUBGROUP/MY_PROJECT/-/commit/56f016eb16ff32911c2a76825acfc7093cc48e62)

**Comment by shumphrey** [comment]
I can recreate this.
I'll have a fix shortly.

**Comment by shumphrey** [comment]
Navigating around the UI, GitLab now seems to put a /-/ inbetween most URLs.
The URL without /-/ works for most things, but not commit.
I'm wondering whether I should change all URLs to the /-/ version

**Comment by shumphrey** [comment]
The question is when they made that change.
How safe is it to break this plugin for people running older versions of self-hosted GitLab

**Comment by phantomwhale** [comment]
Looks like more info here - https://gitlab.com/gitlab-org/gitlab/-/issues/214217

**Comment by shumphrey** [comment]
Thanks for the link.
I've updated the code to support the new url format.
For those on older GitLabs, I've added a variable they can specify for old style URLs
