### ISSUE TITLE
Commit Links Changed

### ISSUE THREAD

**Issue by trsdln** [shumphrey/fugitive-gitlab.vim#45]
Last week Gitlab changed slightly path to commit links:

* Old: https://gitlab.com/test-org/test-repo/commit/6f8ca0922cfc7e31ddb736818f05039c37789a54
* New: https://gitlab.com/test-org/test-repo/-/commit/6f8ca0922cfc7e31ddb736818f05039c37789a54

I thought that it was bug, but looks like changes will stay.

**UPDATE**: Relevant issue: https://gitlab.com/gitlab-org/gitlab/-/issues/28848#release-notes

**Comment by shumphrey** [comment]
This was already changed in #44 please update to the latest version
