### ISSUE TITLE
Access token read from some command?

### ISSUE THREAD

**Issue by ferdinandyb** [shumphrey/fugitive-gitlab.vim#46]
I version control my .vimrc publicly, so if possible I'd to read the access token from a command or file. Is this possible somehow?

**Comment by shumphrey** [comment]
You can source other vim files from your main one.
I source control my main file and conditionally source a local file if it exists.
The local file contains private things.

**Comment by ferdinandyb** [comment]
On Thu Aug 03, 2023 at 13:38, Steven Humphrey wrote:
> You can source other vim files from your main one.
> I source control my main file and conditionally source a local file if it exists.
> The local file contains private things.

LOL, I think my brain stopped working when I wrote this issue. Yeah, that makes
perfect sense, sorry about the noise ...

**Comment by shumphrey** [comment]
No worries

**Comment by ferdinandyb** [comment]
Actually, now that I think about it, since we run vimscript for the variables anyway, you can do basically whatever you want, e.g.:

```
let g:gitlab_api_keys = {'domain': readfile(expand('~/.config/glab-cli/token'))[0]  }
```
