### ISSUE TITLE
Gbrowse is creating the wrong URL

### ISSUE THREAD

**Issue by ferdinandyb** [shumphrey/fugitive-gitlab.vim#47]
My company is self-hosting gitlab. The url on the website to a particular file is 
```
https://[domain]/cat_projects/frida/blob/master/fridapoc.py
```

but `:GBrowse!` prints 

```
https://[domain]/cat_projects/frida/-/blob/master/fridapoc.py
```
, notice the extra `-`. 

I thought maybe it's because of the different address for `ssh` connections, so I tried setting:

```
let g:fugitive_gitlab_domains = {'ssh://[domain]:[port]/': 'https://[domain]/'}
```

but then I get an error:

```
fugitive: no GBrowse handler installed for 'ssh://git@[domain]:[port]/cat_projects/frida.git'
```

Do you have any idea what could be the issue?

**Comment by shumphrey** [comment]
There are instructions for legacy URLs in the readme
