### ISSUE TITLE
How to configure this in neovim/lua? 

### ISSUE THREAD

**Issue by V4G4X** [shumphrey/fugitive-gitlab.vim#48]
I am using neovim.  

I have fugitive, and fugitive-gitlab both installed. 
Lazy.nvim seems to install both successfully. I know this because I've used Fugitive for a while.

I have the following function:
```lua
function ConfigGitlab()
    vim.g.fugitive_gitlab_domains['ssh://git@gitlab.company.com:121112'] = 'https://gitlab.company.com:3344'
end
```

But when I call this, I get:
```
Error detected while processing /Users/v4g4x/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/v4g4x/.config/nvim/lua/core/gitlab.lua:3: attempt to index field 'fugitive_gitlab_domains' (a nil value)
```

Clearly, I'm not converting the vim option from Vimscript to Lua correctly.  
Any help on how this may be done?

**Comment by shumphrey** [comment]
The error messaging is saying that `vim.g.fugitive_gitlab_domains` doesn't exist when you are trying to use, and that you need to create it first.

I don't know lua well, but something like:

```lua
vim.g.fugitive_gitlab_domains = {}
vim.g.fugitive_gitlab_domains['ssh://git@gitlab.company.com:121112'] = 'https://gitlab.company.com:3344'
```
