### ISSUE TITLE
Unable to find Gbrowse handler

### ISSUE THREAD

**Issue by V4G4X** [shumphrey/fugitive-gitlab.vim#49]
When I do `:GBrowse` (in a file where I can see git blame properly) I get:
```
fugitive: no GBrowse handler installed for 'ssh://git@gitlab.company_name.cntry:12112/project_name/repo_name.git'
```

My configuration(using neovim and lua, but no syntax errors) is: 
```lua
    vim.g.fugitive_gitlab_domains = { ['ssh://git@gitlab.gitlab.cntry:12112'] = 'https://gitlab.company_name.cntry:3344' }
    vim.g.gitlab_api_keys = { ['https://gitlab.company_name.cntry:3344'] = 'newly_generated_access_key' }
```

Is it so that the GitLab domains are supposed to contain the project and repo names as well?

**Comment by shumphrey** [comment]
Not an expert on lua, but its probably roughly correct.
`ssh://git@gitlab.gitlab.cntry:12112` doesn't contain "company_name", I'm not sure if that's an artifact of you obfuscating your company name or not.

My guess is those domains aren't quite right.
Whatever fugitive passes to this plugin is what should match in fugitive_gitlab_domains.

Try running `git remote -v` and checking it matches.

**Comment by shumphrey** [comment]
Try setting it to
```lua
vim.g.fugitive_gitlab_domains = { ['gitlab.company_name.cntry'] = 'https://gitlab.company_name.cntry:3344' }
```

i.e. remove the protocol and port from the lua table key

**Comment by V4G4X** [comment]
I used the values on `git remote -v` only.

I removed the SSH protocol. (Didn't remove the port because I felt it wouldn't work. without it) 

Now on `:GBrowse` the error changes. I get:
```
Netrw not found. Define your own :Browse to use :GBrowse
```

# P.S Oh wow, after I disabled `nvim-tree` and `oil.nvim` this worked.

But I use those plugins a lot though.  Do you not use these?  

If I wanted to continue using them, how would defining my own `Browse` look like?

**Comment by V4G4X** [comment]
NVM.  
I found this: https://vi.stackexchange.com/a/43348/50670

And wow it worked beautifully!!
It immediately snaps up the file in GitLab and I can immediately:
1. See who to blame for each line in one click.
2. And jump to that commit (and MR) in single successive clicks respectively. 

Thanks a lot @shumphrey 
You're a God 😭🔥
