### ISSUE TITLE
Can not map custom gitlab instance

### ISSUE THREAD

**Issue by praiskup** [shumphrey/fugitive-gitlab.vim#51]
I'm getting this error:

```
fugitive: no GBrowse handler installed for 'git@my.gitlab.example.com:owner/project.git'
```

Even though I do:

```
let g:fugitive_gitlab_domains = [ 'my.gitlab.example.com' ]
```

**Comment by shumphrey** [comment]
Any chance I can see the real output of `git remote -v`?
There are specific test cases for that basic construct https://github.com/shumphrey/fugitive-gitlab.vim/blob/3584cf7e607ba7822f991d407a8d780e05aae287/test/homepage_for_remote.vader#L11-L14 so I'd need an example vimrc and real domain output to advise further

**Comment by shumphrey** [comment]
oh, you're missing https:// 
`let g:fugitive_gitlab_domains = [ 'https://my.gitlab.example.com' ]`

**Comment by praiskup** [comment]
> oh, you're missing https://

Oh, you are right.  @shumphrey thank you for taking a look, and sorry for the noise!
