### ISSUE TITLE
:Gbrowse <branch> does not work

### ISSUE THREAD

**Issue by WouterSioen** [shumphrey/fugitive-gitlab.vim#6]
It only seems to work for the master branch.

**Comment by shumphrey** [comment]
What version of fugitive do you have?
Does your branch exist on the gitlab server?

**Comment by shumphrey** [comment]
hmm, this used to work. Recent changes to fugitive itself seem to have changed it.
I don't appear to receive the branch from fugitive any more.

**Comment by shumphrey** [comment]
It is unclear from the fugitive docs if that's supposed to work.

    :help fugitive-revision

You can type

    :Gbrowse <branch>:

And you'll get a tree view of master

    :Gbrowse -

And you'll get the file tied to this commit etc. I am unclear on whether <code>:Gbrowse branch</code> by itself is still supposed to work without the : on the end

**Comment by shumphrey** [comment]
I tested with a freshly checked out repo. If the branch exists on gitlab and local this does work.

**Comment by WouterSioen** [comment]
hmm, it seems to work with some branches and not with others. I try to figure out what the difference is.

**Comment by WouterSioen** [comment]
The difference is that some of my branches are specified in my .git/config file.
Others aren't (because I changed my push strategy to "current", to avoid needing to use the `git push --set-upstream` command).

The branches that aren't specified in my .git/config file don't work.

**Comment by shumphrey** [comment]
Yeah, this relies on whatever fugitive.vim sends to this plugin.
It seems to get the branch from the .git/config settings and if you don't have that, it doesn't work, I suspect that's the best it can do, so you'll have to set the upstream branch.
Being reliant on what fugitive sends, I'm going to close this.
Feel free to follow this up with fugitive.

**Comment by WouterSioen** [comment]
Ok, thanks for looking in to this!

**Comment by WouterSioen** [comment]
Note: I've added an issue for this here: https://github.com/tpope/vim-fugitive/issues/748
