### ISSUE TITLE
Double username/projectname

### ISSUE THREAD

**Issue by stefthoen** [shumphrey/fugitive-gitlab.vim#9]
When I open a file with `:Gbrowse` it goes to https://gitlab.com/baardbaard/my-project/baardbaard/my-project/blob/etc. Any idea what could be the problem? 

Thanks!

**Comment by shumphrey** [comment]
Hi @baardbaard 

Can you show me the output of

    git remote -v

And are you running the latest version of both fugitive and fugitive-gitlab ?

**Comment by stefthoen** [comment]
Replaced username and projectname with placeholders. Rest of output is the same. Was running latest version of `fugitive` and `fugitive-lab`.

```
origin  git@gitlab.com:myusername/myproject.git (fetch)
origin  git@gitlab.com:myusername/myproject.git (push)
```

Had this issue yesterday on a branch I was working on. Got merged today and can't seem to reproduce, and other branches seem to work just fine. You can close this if you want to. If it happens again I'll open a new ticket and make sure I can reproduce.

**Comment by shumphrey** [comment]
ok, I'll close for now.
Feel free to re-open/create new if you can recreate.
